name: tv
description: "A new Flutter project."

# Prevent publishing to pub.dev since this is a private project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Your private GitHub repo dependency


  # Public dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  android_intent_plus: ^5.3.1
  appcheck: ^1.5.4+1
  carousel_slider: ^5.1.1
  share_plus: ^11.1.0
  marquee: ^2.3.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
